version: '3.8'

services:
  storage-api:
    image: tutitoos/storage-api:latest
    container_name: storage-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4003:4003"
      - "4004:4004"
    env_file:
      - .env
